# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/TEXT_VGA/TEXT_VGA.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/TEXT_VGA/TEXT_VGA.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/TEXT_VGA/TEXT_VGA.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -vhdl2008 -library xil_defaultlib {
  {C:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/project_vhdl/src/commonPak.vhd}
  {C:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/project_vhdl/src/sipo.vhd}
  {C:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/project_vhdl/src/driver_keyboard.vhd}
  {C:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/project_vhdl/src/editor.vhd}
  {C:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/project_vhdl/src/fsm_keyboard.vhd}
  {C:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/project_vhdl/src/counter.vhd}
  {C:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/project_vhdl/src/image_generator.vhd}
  {C:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/project_vhdl/src/seven_segment_driver.vhd}
  {C:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/project_vhdl/src/stream.vhd}
  {C:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/project_vhdl/src/frame_buffer.vhd}
  {C:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/project_vhdl/src/vga_controller.vhd}
  {C:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/project_vhdl/src/fonts_ROM.vhd}
  {C:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/project_vhdl/src/top_level_keyboard.vhd}
  {C:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/project_vhdl/src/top_level_project.vhd}
}
read_ip -quiet {{C:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/TEXT_VGA/TEXT_VGA.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/TEXT_VGA/TEXT_VGA.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc}}]

read_ip -quiet {{C:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/TEXT_VGA/TEXT_VGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/TEXT_VGA/TEXT_VGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/TEXT_VGA/TEXT_VGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/TEXT_VGA/TEXT_VGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc}}]

read_ip -quiet {{C:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/TEXT_VGA/TEXT_VGA.srcs/sources_1/ip/blk_mem_gen_1_1/blk_mem_gen_1.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/TEXT_VGA/TEXT_VGA.srcs/sources_1/ip/blk_mem_gen_1_1/blk_mem_gen_1_ooc.xdc}}]

read_ip -quiet {{C:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/TEXT_VGA/TEXT_VGA.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/TEXT_VGA/TEXT_VGA.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/project_vhdl/constraints.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/project_vhdl/constraints.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_level_project -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_level_project.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_level_project_utilization_synth.rpt -pb top_level_project_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
