# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/TEXT_VGA/TEXT_VGA.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci
# IP: The module: 'blk_mem_gen_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/TEXT_VGA/TEXT_VGA.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/TEXT_VGA/TEXT_VGA.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci
# IP: The module: 'blk_mem_gen_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Luca/Google Drive/secondo anno universita/elettronica/VHDL/ProgettoELE3/TEXT_VGA/TEXT_VGA.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
